//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dahab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int ID { get; set; }
        public int Code1 { get; set; }
        public double Discount { get; set; }
    }
}
