//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dahab.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int User_ID { get; set; }
        [Required(ErrorMessageResourceName = "NameRequired", ErrorMessageResourceType = typeof(APIResource))]
        public string Name { get; set; }
        [Required(ErrorMessageResourceName = "PhoneRequired", ErrorMessageResourceType = typeof(APIResource))]
        [Phone(ErrorMessageResourceName = "InvalidPhone", ErrorMessageResourceType = typeof(APIResource))]
        public string Phone { get; set; }
        [Required(ErrorMessageResourceName = "RequiredCity", ErrorMessageResourceType = typeof(APIResource))]
        public string City { get; set; }
        [Required(ErrorMessageResourceName = "RequiredPlace", ErrorMessageResourceType = typeof(APIResource))]
        public string Place { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Log { get; set; }
        public bool UseVisa { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public string DiscountType { get; set; }
        public double FinalPrice { get; set; }
        public bool IsArriveToUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual User User { get; set; }
    }
}
