//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dahab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dahab.APIResource", typeof(APIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Add This Product To Your Favorites Successfuly ..
        /// </summary>
        internal static string AddFaveDone {
            get {
                return ResourceManager.GetString("AddFaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Product From Favorites ..
        /// </summary>
        internal static string DeleteFavDone {
            get {
                return ResourceManager.GetString("DeleteFavDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete From Favorite .. User Or Favorite Not Found .
        /// </summary>
        internal static string DeleteFavError {
            get {
                return ResourceManager.GetString("DeleteFavError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit Your Profile Successfuly ..
        /// </summary>
        internal static string EditProfileDone {
            get {
                return ResourceManager.GetString("EditProfileDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter Your E-Mail Address.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Registered Using Your FaceBook Account.
        /// </summary>
        internal static string FacebookUserFound {
            get {
                return ResourceManager.GetString("FacebookUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter Your First Name .
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code Is Not Correct ..
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter A Valid E-Mail Address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter A Valid Phone Number.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Like This Product.
        /// </summary>
        internal static string IsLiked {
            get {
                return ResourceManager.GetString("IsLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter Your Last Name.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You For Login .. Welcome In Wahag.
        /// </summary>
        internal static string LoginDone {
            get {
                return ResourceManager.GetString("LoginDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Not Found Please Enter Valid Data.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter You Name .
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Create A new Order Successfuly . Thank You ..
        /// </summary>
        internal static string OrderDone {
            get {
                return ResourceManager.GetString("OrderDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter Your Phone Number.
        /// </summary>
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Product Not Found ..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Products Data Valid ..
        /// </summary>
        internal static string ProductsValid {
            get {
                return ResourceManager.GetString("ProductsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Create New Account Successfuly ..
        /// </summary>
        internal static string RegisterDone {
            get {
                return ResourceManager.GetString("RegisterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter You City.
        /// </summary>
        internal static string RequiredCity {
            get {
                return ResourceManager.GetString("RequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please . Enter Your Place.
        /// </summary>
        internal static string RequiredPlace {
            get {
                return ResourceManager.GetString("RequiredPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This E-Mail Is Used Before .. Please Try Another One.
        /// </summary>
        internal static string UniqueEmail {
            get {
                return ResourceManager.GetString("UniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found !.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
